Update Release 5 Concept - Runcheck Function and Notes

diff --git a/Release 5 Concept - Runcheck Function and Notes b/Release 5 Concept - Runcheck Function and Notes
--- a/Release 5 Concept - Runcheck Function and Notes
+++ b/Release 5 Concept - Runcheck Function and Notes
@@ -36,3 +36,40 @@ runcheck () {
 	fi
 	IFS=""
 }
+
+An alternative version of the same function is included below for commands that may need a different IFS. However, unless you are facing issues, the original function should be used most of the time.
+
+runcheck2 () {
+	IFS=$' \t\n'
+	command="$*"
+	retval=1
+	attempt=1
+	until [[ $retval -eq 0 ]] || [[ $attempt -gt 5 ]]; do
+		(
+			set +e
+			$command
+		)
+		retval=$?
+		attempt=$(( $attempt + 1 ))
+		if [[ $retval -ne 0 ]]; then
+			clear
+			tput setaf 9
+			echo "Oops! Something went wrong! Retrying in 3 seconds..."
+			tput sgr0
+			sleep 3
+			clear
+		fi
+	done
+	if [[ $retval -ne 0 ]] && [[ $attempt -gt 5 ]]; then
+		clear
+		tput setaf 9
+		echo "Oops! A fatal error has occurred and the program cannot continue. Returning to the main menu in 10 seconds..."
+		tput setaf 3
+		echo "Please try again later or if the problem persists, create an issue on GitHub."
+		tput sgr0
+		sleep 10
+		clear
+		mainmenu
+	fi
+	IFS=""
+}
